import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/Navbar';
import { Sidebar } from '@/components/Sidebar';
import { FooterWithSitemap } from '@/components/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body className="flex h-scren flex-col  ">
        <div className="flex flex-col flex-1">
          <Navbar />
          <main className="p-6">
        {/* <Sidebar /> */}
            {children}
            </main>
        </div>
        <div className="flex flex-col m-5 ">
          <FooterWithSitemap />
        </div>
        
      </body>
    </html>
  );
}
